### PR TITLE
fix(types): fix the types

### PR DESCRIPTION
**Pull request by boneskull**
- I missed that the default export is actually an instance
- And that Loggerr is a property of that instance
- Also added more tests and reformatted

### CODE REVIEW

**Comment by boneskull** [comment]
@wesleytodd I notice that the `levels` option mostly appears to be an array of strings, but in the `cli` formatter, it's a mapping of level name to color.  Can/should all formatters use both formats?

**Comment by wesleytodd** [comment]
Oops, sorry this got lost in the pile as I was traveling.

> it's a mapping of level name to color. Can/should all formatters use both formats?

I think that was the only one doing that. The general idea was that someone could create their own formatter as long as the api was `fmt(opts): (date, level, data) => string` (pardon the likely wrong annotation, I hate my life)

So those options are defined *by* the formatter. I would type them individually and try to make clear the interface is open ended.

**Comment by boneskull** [comment]
@wesleytodd for my purposes (since I'm not making a formatter) I would choose to punt on the fact that the formatter has any impact on the options.  I'll add a note about it.

**Comment by wesleytodd** [comment]
Sounds good to me.

**Comment by boneskull** [comment]
Sorry, I got nerd-sniped and actually implemented it.

**Comment by boneskull** [comment]
@wesleytodd This is ready IMO.

I ended up touching `index.js` just to tell TS to ignore it.

**Comment by boneskull** [comment]
I should probably mention that since the types directly consume `WritableStream` from [@types/node](https://npm.im/@types/node), including `@types/node` as a production dependency is best practice.  I didn't want to do this because I am trying to not fuck with anything.

Failing that, I threw a directive in there that _should_ cause compatible editors to automatically fetch `@types/node` if not present.

**Review by wesleytodd — APPROVED** [review]
I just want to point out the types are not longer than the code.

**Comment by wesleytodd** [comment]
`loggerr@4.2.0`

**Pull request merged**
